package pl.idzikpro.xcom.service.soldiers;

public class SoldierStatsRepository {
    public static SoldierStats getRookieStats() {
        return rookieStats;
    }

    public static SoldierStats getSquaddieStats() {
        return squaddieStats;
    }

    public static SoldierStats getSergeantStats() {
        return sergeantStats;
    }

    public static SoldierStats getCaptainStats() {
        return captainStats;
    }

    public static SoldierStats getColonelStats() {
        return colonelStats;
    }

    public static SoldierStats getCommanderStats() {
        return commanderStats;
    }

    private static SoldierStats rookieStats = SoldierStats.builder()
            .rank("rookie")
            .timeUnitsMin(50)
            .timeUnitsMax(60)
            .energyMin(40)
            .energyMax(70)
            .healthMin(25)
            .healthMax(40)
            .braveryMin(10)
            .braveryMax(60)
            .reactionsMin(30)
            .reactionsMax(60)
            .firingAccuracyMin(40)
            .firingAccuracyMax(70)
            .throwingAccuracyMin(50)
            .throwingAccuracyMax(80)
            .strengthMin(20)
            .strengthMax(40)
            .psiSkillMin(16)
            .psiSkillMax(24)
            .psiStrengthMin(0)
            .psiStrengthMax(100)
            .meleeAccuracyMin(20)
            .meleeAccuracyMax(40)
            .missionsMix(0)
            .missionsMax(0)
            .killedMin(0)
            .killedMax(0)
            .build();

    private static SoldierStats squaddieStats = SoldierStats.builder()
            .rank("squaddie")
            .timeUnitsMin(52)
            .timeUnitsMax(60)
            .energyMin(40)
            .energyMax(70)
            .healthMin(25)
            .healthMax(40)
            .braveryMin(12)
            .braveryMax(60)
            .reactionsMin(32)
            .reactionsMax(60)
            .firingAccuracyMin(42)
            .firingAccuracyMax(70)
            .throwingAccuracyMin(50)
            .throwingAccuracyMax(80)
            .strengthMin(20)
            .strengthMax(40)
            .psiSkillMin(16)
            .psiSkillMax(24)
            .psiStrengthMin(0)
            .psiStrengthMax(100)
            .meleeAccuracyMin(22)
            .meleeAccuracyMax(40)
            .missionsMix(1)
            .missionsMax(20)
            .killedMin(1)
            .killedMax(10)
            .build();

    private static SoldierStats sergeantStats = SoldierStats.builder()
            .rank("sergeant")
            .timeUnitsMin(54)
            .timeUnitsMax(64)
            .energyMin(44)
            .energyMax(78)
            .healthMin(30)
            .healthMax(50)
            .braveryMin(16)
            .braveryMax(70)
            .reactionsMin(38)
            .reactionsMax(66)
            .firingAccuracyMin(52)
            .firingAccuracyMax(80)
            .throwingAccuracyMin(60)
            .throwingAccuracyMax(88)
            .strengthMin(30)
            .strengthMax(50)
            .psiSkillMin(36)
            .psiSkillMax(44)
            .psiStrengthMin(20)
            .psiStrengthMax(100)
            .meleeAccuracyMin(28)
            .meleeAccuracyMax(50)
            .missionsMix(5)
            .missionsMax(20)
            .killedMin(3)
            .killedMax(20)
            .build();

    private static SoldierStats captainStats = SoldierStats.builder()
            .rank("captain")
            .timeUnitsMin(64)
            .timeUnitsMax(84)
            .energyMin(54)
            .energyMax(88)
            .healthMin(40)
            .healthMax(80)
            .braveryMin(30)
            .braveryMax(80)
            .reactionsMin(40)
            .reactionsMax(70)
            .firingAccuracyMin(70)
            .firingAccuracyMax(90)
            .throwingAccuracyMin(70)
            .throwingAccuracyMax(90)
            .strengthMin(36)
            .strengthMax(60)
            .psiSkillMin(40)
            .psiSkillMax(60)
            .psiStrengthMin(30)
            .psiStrengthMax(100)
            .meleeAccuracyMin(30)
            .meleeAccuracyMax(60)
            .missionsMix(10)
            .missionsMax(30)
            .killedMin(10)
            .killedMax(30)
            .build();

    private static SoldierStats colonelStats = SoldierStats.builder()
            .rank("colonel")
            .timeUnitsMin(70)
            .timeUnitsMax(90)
            .energyMin(60)
            .energyMax(90)
            .healthMin(50)
            .healthMax(90)
            .braveryMin(40)
            .braveryMax(90)
            .reactionsMin(50)
            .reactionsMax(80)
            .firingAccuracyMin(80)
            .firingAccuracyMax(100)
            .throwingAccuracyMin(80)
            .throwingAccuracyMax(95)
            .strengthMin(40)
            .strengthMax(70)
            .psiSkillMin(50)
            .psiSkillMax(80)
            .psiStrengthMin(40)
            .psiStrengthMax(110)
            .meleeAccuracyMin(50)
            .meleeAccuracyMax(70)
            .missionsMix(20)
            .missionsMax(40)
            .killedMin(15)
            .killedMax(40)
            .build();

    private static SoldierStats commanderStats = SoldierStats.builder()
            .rank("commander")
            .timeUnitsMin(70)
            .timeUnitsMax(120)
            .energyMin(60)
            .energyMax(100)
            .healthMin(60)
            .healthMax(100)
            .braveryMin(50)
            .braveryMax(100)
            .reactionsMin(60)
            .reactionsMax(90)
            .firingAccuracyMin(85)
            .firingAccuracyMax(120)
            .throwingAccuracyMin(90)
            .throwingAccuracyMax(100)
            .strengthMin(50)
            .strengthMax(90)
            .psiSkillMin(60)
            .psiSkillMax(100)
            .psiStrengthMin(50)
            .psiStrengthMax(120)
            .meleeAccuracyMin(60)
            .meleeAccuracyMax(80)
            .missionsMix(30)
            .missionsMax(60)
            .killedMin(20)
            .killedMax(60)
            .build();
}
