package pl.idzikpro.xcom.service.aliens;

import lombok.Data;
import pl.idzikpro.xcom.service.aliens.AlienStats;

import java.util.Arrays;

@Data
public class AlienStatsRepository {
    public static AlienStats getCelatidStats() {
        return celatidStats;
    }

    public static AlienStats getChryssalidStats() {
        return chryssalidStats;
    }

    public static AlienStats getCyberdiscStats() {
        return cyberdiscStats;
    }

    public static AlienStats getEtherealStats() {
        return etherealStats;
    }

    public static AlienStats getFloaterStats() {
        return floaterStats;
    }

    public static AlienStats getMutonStats() {
        return mutonStats;
    }

    public static AlienStats getReaperStats() {
        return reaperStats;
    }

    public static AlienStats getSectoidStats() {
        return sectoidStats;
    }

    public static AlienStats getSectopodStats() {
        return sectopodStats;
    }

    public static AlienStats getSilacoidStats() {
        return silacoidStats;
    }

    public static AlienStats getSnakemanStats() {
        return snakemanStats;
    }

    public static AlienStats getZombieStats() {
        return zombieStats;
    }

    private static AlienStats celatidStats = AlienStats.builder()
            .name("celatid")
            .timeUnitsMin(70)
            .timeUnitsMax(81)
            .healthMin(62)
            .healthMax(62)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(40)
            .reactionsMax(49)
            .strengthMin(70)
            .strengthMax(75)
            .braveryMin(90)
            .braveryMax(90)
            .firingAccuracyMin(50)
            .firingAccuracyMax(124)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(60)
            .psiStrengthMax(69)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(20)
            .armourFrontMax(20)
            .armourLeftMin(20)
            .armourLeftMax(20)
            .armourRightMin(20)
            .armourRightMax(20)
            .armourRearMin(20)
            .armourRearMax(20)
            .armourUnderMin(20)
            .armourUnderMax(20)
            .energyRecoveryMin(40)
            .energyRecoveryMax(40)
            .victoryPointsMin(20)
            .victoryPointsMax(20)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(4)
            .intelligenceMax(4)
            .heightStandingMin(16)
            .heightStandingMax(16)
            .heightKneelingMin(16)
            .heightKneelingMax(16)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();


    private static AlienStats chryssalidStats = AlienStats.builder()
            .name("chryssalid")
            .timeUnitsMin(110)
            .timeUnitsMax(127)
            .healthMin(96)
            .healthMax(96)
            .energyMin(140)
            .energyMax(162)
            .reactionsMin(70)
            .reactionsMax(86)
            .strengthMin(110)
            .strengthMax(118)
            .braveryMin(100)
            .braveryMax(100)
            .firingAccuracyMin(0)
            .firingAccuracyMax(0)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(50)
            .psiStrengthMax(69)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(34)
            .armourFrontMax(34)
            .armourLeftMin(34)
            .armourLeftMax(34)
            .armourRightMin(34)
            .armourRightMax(34)
            .armourRearMin(34)
            .armourRearMax(34)
            .armourUnderMin(34)
            .armourUnderMax(34)
            .energyRecoveryMin(40)
            .energyRecoveryMax(40)
            .victoryPointsMin(25)
            .victoryPointsMax(25)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(4)
            .intelligenceMax(4)
            .heightStandingMin(16)
            .heightStandingMax(16)
            .heightKneelingMin(16)
            .heightKneelingMax(16)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();

    private static AlienStats cyberdiscStats = AlienStats.builder()
            .name("cyberdisc")
            .timeUnitsMin(62)
            .timeUnitsMax(71)
            .healthMin(120)
            .healthMax(120)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(64)
            .reactionsMax(79)
            .strengthMin(90)
            .strengthMax(97)
            .braveryMin(110)
            .braveryMax(110)
            .firingAccuracyMin(30)
            .firingAccuracyMax(70)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(100)
            .psiStrengthMax(116)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(34)
            .armourFrontMax(34)
            .armourLeftMin(34)
            .armourLeftMax(34)
            .armourRightMin(34)
            .armourRightMax(34)
            .armourRearMin(34)
            .armourRearMax(34)
            .armourUnderMin(34)
            .armourUnderMax(34)
            .energyRecoveryMin(50)
            .energyRecoveryMax(50)
            .victoryPointsMin(20)
            .victoryPointsMax(20)
            .aggressionMin(1)
            .aggressionMax(1)
            .intelligenceMin(5)
            .intelligenceMax(5)
            .heightStandingMin(20)
            .heightStandingMax(20)
            .heightKneelingMin(20)
            .heightKneelingMax(20)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();

    private static AlienStats etherealStats = AlienStats.builder()
            .name("ethereal")
            .timeUnitsMin(68)
            .timeUnitsMax(78)
            .healthMin(55)
            .healthMax(55)
            .energyMin(96)
            .energyMax(111)
            .reactionsMin(75)
            .reactionsMax(93)
            .strengthMin(48)
            .strengthMax(51)
            .braveryMin(80)
            .braveryMax(80)
            .firingAccuracyMin(37)
            .firingAccuracyMax(91)
            .throwingAccuracyMin(80)
            .throwingAccuracyMax(80)
            .psiSkillMin(40)
            .psiSkillMax(58)
            .psiStrengthMin(50)
            .psiStrengthMax(75)
            .meleeAccuracyMin(85)
            .meleeAccuracyMax(85)
            .armourFrontMin(35)
            .armourFrontMax(45)
            .armourLeftMin(35)
            .armourLeftMax(45)
            .armourRightMin(35)
            .armourRightMax(45)
            .armourRearMin(35)
            .armourRearMax(45)
            .armourUnderMin(35)
            .armourUnderMax(45)
            .energyRecoveryMin(40)
            .energyRecoveryMax(40)
            .victoryPointsMin(20)
            .victoryPointsMax(40)
            .aggressionMin(1)
            .aggressionMax(1)
            .intelligenceMin(6)
            .intelligenceMax(8)
            .heightStandingMin(20)
            .heightStandingMax(20)
            .heightKneelingMin(16)
            .heightKneelingMax(16)
            .validRankSoldier(true)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(false)
            .validRankLeader(true)
            .validRankCommander(true)
            .validRanks(Arrays.asList("soldier", "leader", "commander")).build();

    private static AlienStats floaterStats = AlienStats.builder()
            .name("floater")
            .timeUnitsMin(50)
            .timeUnitsMax(69)
            .healthMin(35)
            .healthMax(45)
            .energyMin(90)
            .energyMax(116)
            .reactionsMin(50)
            .reactionsMax(81)
            .strengthMin(40)
            .strengthMax(51)
            .braveryMin(80)
            .braveryMax(80)
            .firingAccuracyMin(25)
            .firingAccuracyMax(78)
            .throwingAccuracyMin(58)
            .throwingAccuracyMax(65)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(35)
            .psiStrengthMax(52)
            .meleeAccuracyMin(70)
            .meleeAccuracyMax(70)
            .armourFrontMin(8)
            .armourFrontMax(24)
            .armourLeftMin(6)
            .armourLeftMax(18)
            .armourRightMin(6)
            .armourRightMax(18)
            .armourRearMin(4)
            .armourRearMax(12)
            .armourUnderMin(12)
            .armourUnderMax(16)
            .energyRecoveryMin(30)
            .energyRecoveryMax(30)
            .victoryPointsMin(12)
            .victoryPointsMax(35)
            .aggressionMin(0)
            .aggressionMax(2)
            .intelligenceMin(4)
            .intelligenceMax(8)
            .heightStandingMin(18)
            .heightStandingMax(18)
            .heightKneelingMin(14)
            .heightKneelingMax(14)
            .validRankSoldier(true)
            .validRankNavigator(true)
            .validRankMedic(true)
            .validRankEngineer(true)
            .validRankTerrorist(false)
            .validRankLeader(true)
            .validRankCommander(true)
            .validRanks(Arrays.asList("soldier", "navigator", "medic", "engineer", "leader", "commander")).build();

    private static AlienStats mutonStats = AlienStats.builder()
            .name("muton")
            .timeUnitsMin(56)
            .timeUnitsMax(64)
            .healthMin(125)
            .healthMax(125)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(60)
            .reactionsMax(74)
            .strengthMin(70)
            .strengthMax(75)
            .braveryMin(80)
            .braveryMax(80)
            .firingAccuracyMin(27)
            .firingAccuracyMax(66)
            .throwingAccuracyMin(62)
            .throwingAccuracyMax(62)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(25)
            .psiStrengthMax(29)
            .meleeAccuracyMin(78)
            .meleeAccuracyMax(78)
            .armourFrontMin(20)
            .armourFrontMax(20)
            .armourLeftMin(20)
            .armourLeftMax(20)
            .armourRightMin(20)
            .armourRightMax(20)
            .armourRearMin(20)
            .armourRearMax(20)
            .armourUnderMin(10)
            .armourUnderMax(20)
            .energyRecoveryMin(40)
            .energyRecoveryMax(40)
            .victoryPointsMin(15)
            .victoryPointsMax(19)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(2)
            .intelligenceMax(4)
            .heightStandingMin(18)
            .heightStandingMax(18)
            .heightKneelingMin(14)
            .heightKneelingMax(14)
            .validRankSoldier(true)
            .validRankNavigator(true)
            .validRankMedic(false)
            .validRankEngineer(true)
            .validRankTerrorist(false)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("soldier", "navigator", "engineer")).build();

    private static AlienStats reaperStats = AlienStats.builder()
            .name("reaper")
            .timeUnitsMin(62)
            .timeUnitsMax(71)
            .healthMin(148)
            .healthMax(148)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(64)
            .reactionsMax(79)
            .strengthMin(90)
            .strengthMax(97)
            .braveryMin(90)
            .braveryMax(90)
            .firingAccuracyMin(0)
            .firingAccuracyMax(0)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(35)
            .psiStrengthMax(40)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(28)
            .armourFrontMax(28)
            .armourLeftMin(28)
            .armourLeftMax(28)
            .armourRightMin(28)
            .armourRightMax(28)
            .armourRearMin(28)
            .armourRearMax(28)
            .armourUnderMin(4)
            .armourUnderMax(4)
            .energyRecoveryMin(34)
            .energyRecoveryMax(34)
            .victoryPointsMin(25)
            .victoryPointsMax(25)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(2)
            .intelligenceMax(2)
            .heightStandingMin(22)
            .heightStandingMax(22)
            .heightKneelingMin(22)
            .heightKneelingMax(22)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();

    private static AlienStats sectoidStats = AlienStats.builder()
            .name("sectoid")
            .timeUnitsMin(54)
            .timeUnitsMax(62)
            .healthMin(30)
            .healthMax(30)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(63)
            .reactionsMax(78)
            .strengthMin(30)
            .strengthMax(32)
            .braveryMin(80)
            .braveryMax(80)
            .firingAccuracyMin(26)
            .firingAccuracyMax(64)
            .throwingAccuracyMin(58)
            .throwingAccuracyMax(58)
            .psiSkillMin(40)
            .psiSkillMax(58)
            .psiStrengthMin(50)
            .psiStrengthMax(69)
            .meleeAccuracyMin(76)
            .meleeAccuracyMax(76)
            .armourFrontMin(2)
            .armourFrontMax(4)
            .armourLeftMin(1)
            .armourLeftMax(3)
            .armourRightMin(1)
            .armourRightMax(3)
            .armourRearMin(1)
            .armourRearMax(2)
            .armourUnderMin(1)
            .armourUnderMax(2)
            .energyRecoveryMin(30)
            .energyRecoveryMax(30)
            .victoryPointsMin(10)
            .victoryPointsMax(20)
            .aggressionMin(1)
            .aggressionMax(2)
            .intelligenceMin(3)
            .intelligenceMax(7)
            .heightStandingMin(16)
            .heightStandingMax(16)
            .heightKneelingMin(12)
            .heightKneelingMax(12)
            .validRankSoldier(true)
            .validRankNavigator(true)
            .validRankMedic(true)
            .validRankEngineer(true)
            .validRankTerrorist(false)
            .validRankLeader(true)
            .validRankCommander(true)
            .validRanks(Arrays.asList("soldier", "navigator", "medic", "engineer", "leader", "commander")).build();

    private static AlienStats sectopodStats = AlienStats.builder()
            .name("sectopod")
            .timeUnitsMin(62)
            .timeUnitsMax(71)
            .healthMin(96)
            .healthMax(96)
            .energyMin(90)
            .energyMax(104)
            .reactionsMin(64)
            .reactionsMax(79)
            .strengthMin(90)
            .strengthMax(97)
            .braveryMin(110)
            .braveryMax(110)
            .firingAccuracyMin(30)
            .firingAccuracyMax(70)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(100)
            .psiStrengthMax(116)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(145)
            .armourFrontMax(145)
            .armourLeftMin(130)
            .armourLeftMax(130)
            .armourRightMin(130)
            .armourRightMax(130)
            .armourRearMin(100)
            .armourRearMax(100)
            .armourUnderMin(90)
            .armourUnderMax(90)
            .energyRecoveryMin(50)
            .energyRecoveryMax(50)
            .victoryPointsMin(30)
            .victoryPointsMax(30)
            .aggressionMin(1)
            .aggressionMax(1)
            .intelligenceMin(4)
            .intelligenceMax(4)
            .heightStandingMin(22)
            .heightStandingMax(22)
            .heightKneelingMin(22)
            .heightKneelingMax(22)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();
    ;

    private static AlienStats silacoidStats = AlienStats.builder()
            .name("silacoid")
            .timeUnitsMin(40)
            .timeUnitsMax(46)
            .healthMin(114)
            .healthMax(114)
            .energyMin(80)
            .energyMax(92)
            .reactionsMin(40)
            .reactionsMax(49)
            .strengthMin(70)
            .strengthMax(75)
            .braveryMin(100)
            .braveryMax(100)
            .firingAccuracyMin(0)
            .firingAccuracyMax(0)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(80)
            .psiStrengthMax(92)
            .meleeAccuracyMin(50)
            .meleeAccuracyMax(50)
            .armourFrontMin(50)
            .armourFrontMax(50)
            .armourLeftMin(50)
            .armourLeftMax(50)
            .armourRightMin(50)
            .armourRightMax(50)
            .armourRearMin(50)
            .armourRearMax(50)
            .armourUnderMin(10)
            .armourUnderMax(10)
            .energyRecoveryMin(40)
            .energyRecoveryMax(40)
            .victoryPointsMin(20)
            .victoryPointsMax(20)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(3)
            .intelligenceMax(3)
            .heightStandingMin(12)
            .heightStandingMax(12)
            .heightKneelingMin(8)
            .heightKneelingMax(8)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();

    private static AlienStats snakemanStats = AlienStats.builder()
            .name("snakeman")
            .timeUnitsMin(40)
            .timeUnitsMax(52)
            .healthMin(45)
            .healthMax(55)
            .energyMin(80)
            .energyMax(97)
            .reactionsMin(45)
            .reactionsMax(80)
            .strengthMin(47)
            .strengthMax(50)
            .braveryMin(80)
            .braveryMax(80)
            .firingAccuracyMin(29)
            .firingAccuracyMax(71)
            .throwingAccuracyMin(65)
            .throwingAccuracyMax(65)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(40)
            .psiStrengthMax(58)
            .meleeAccuracyMin(54)
            .meleeAccuracyMax(54)
            .armourFrontMin(20)
            .armourFrontMax(26)
            .armourLeftMin(18)
            .armourLeftMax(26)
            .armourRightMin(18)
            .armourRightMax(26)
            .armourRearMin(16)
            .armourRearMax(22)
            .armourUnderMin(12)
            .armourUnderMax(20)
            .energyRecoveryMin(30)
            .energyRecoveryMax(30)
            .victoryPointsMin(15)
            .victoryPointsMax(36)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(2)
            .intelligenceMax(6)
            .heightStandingMin(18)
            .heightStandingMax(18)
            .heightKneelingMin(14)
            .heightKneelingMax(14)
            .validRankSoldier(true)
            .validRankNavigator(true)
            .validRankMedic(false)
            .validRankEngineer(true)
            .validRankTerrorist(false)
            .validRankLeader(true)
            .validRankCommander(true)
            .validRanks(Arrays.asList("soldier", "navigator", "engineer", "leader", "commander")).build();

    private static AlienStats zombieStats = AlienStats.builder()
            .name("zombie")
            .timeUnitsMin(40)
            .timeUnitsMax(40)
            .healthMin(84)
            .healthMax(84)
            .energyMin(110)
            .energyMax(110)
            .reactionsMin(40)
            .reactionsMax(40)
            .strengthMin(84)
            .strengthMax(84)
            .braveryMin(110)
            .braveryMax(110)
            .firingAccuracyMin(0)
            .firingAccuracyMax(0)
            .throwingAccuracyMin(0)
            .throwingAccuracyMax(0)
            .psiSkillMin(0)
            .psiSkillMax(0)
            .psiStrengthMin(80)
            .psiStrengthMax(80)
            .meleeAccuracyMin(80)
            .meleeAccuracyMax(80)
            .armourFrontMin(4)
            .armourFrontMax(4)
            .armourLeftMin(4)
            .armourLeftMax(4)
            .armourRightMin(4)
            .armourRightMax(4)
            .armourRearMin(4)
            .armourRearMax(4)
            .armourUnderMin(4)
            .armourUnderMax(4)
            .energyRecoveryMin(20)
            .energyRecoveryMax(20)
            .victoryPointsMin(18)
            .victoryPointsMax(18)
            .aggressionMin(2)
            .aggressionMax(2)
            .intelligenceMin(3)
            .intelligenceMax(3)
            .heightStandingMin(16)
            .heightStandingMax(16)
            .heightKneelingMin(12)
            .heightKneelingMax(12)
            .validRankSoldier(false)
            .validRankNavigator(false)
            .validRankMedic(false)
            .validRankEngineer(false)
            .validRankTerrorist(true)
            .validRankLeader(false)
            .validRankCommander(false)
            .validRanks(Arrays.asList("terrorist")).build();
}